name: Test 

on:
  [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.15, 1.16, 1.17]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-golang@v2
        with:
          golang-versions: ${{ matrix.golang }}
      - name: Install Dependancies
        run: go mod download
      - name: Run Go Tests
        run: go test -v ./...


